// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPE-buqmIR_s783xQhlGBH7s28MH1M8QM',
    appId: '1:886762066012:web:b80b328906ab21ccd8d699',
    messagingSenderId: '886762066012',
    projectId: 'doctor-appp',
    authDomain: 'doctor-appp.firebaseapp.com',
    storageBucket: 'doctor-appp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybuYGj0LXWSc5trdXqzrt3itBbyjkj34',
    appId: '1:886762066012:android:275c4f46d9a852e5d8d699',
    messagingSenderId: '886762066012',
    projectId: 'doctor-appp',
    storageBucket: 'doctor-appp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8mUSb6kipM4GplRf7LCcvfUMI7FqoJo',
    appId: '1:886762066012:ios:fb14f331d5207b8fd8d699',
    messagingSenderId: '886762066012',
    projectId: 'doctor-appp',
    storageBucket: 'doctor-appp.firebasestorage.app',
    iosBundleId: 'com.example.groupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8mUSb6kipM4GplRf7LCcvfUMI7FqoJo',
    appId: '1:886762066012:ios:fb14f331d5207b8fd8d699',
    messagingSenderId: '886762066012',
    projectId: 'doctor-appp',
    storageBucket: 'doctor-appp.firebasestorage.app',
    iosBundleId: 'com.example.groupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPE-buqmIR_s783xQhlGBH7s28MH1M8QM',
    appId: '1:886762066012:web:e654c7c04e32eba2d8d699',
    messagingSenderId: '886762066012',
    projectId: 'doctor-appp',
    authDomain: 'doctor-appp.firebaseapp.com',
    storageBucket: 'doctor-appp.firebasestorage.app',
  );

}